// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
namespace UI.Resources {
    using System;
    using System.Resources;
    using System.Globalization;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    internal static class Strings {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        internal static ResourceManager ResourceManager {
            get {
                if (resourceMan == null) {
                    resourceMan = new ResourceManager("UI.Resources.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        internal static CultureInfo Culture {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string WindowTitle => ResourceManager.GetString("WindowTitle", resourceCulture);
        internal static string Resource => ResourceManager.GetString("Resource", resourceCulture);
        internal static string Quantity => ResourceManager.GetString("Quantity", resourceCulture);
        internal static string Name => ResourceManager.GetString("Name", resourceCulture);
        internal static string Unit => ResourceManager.GetString("Unit", resourceCulture);
        internal static string Create => ResourceManager.GetString("Create", resourceCulture);
        internal static string QuantityLabel => ResourceManager.GetString("QuantityLabel", resourceCulture);
        internal static string Train => ResourceManager.GetString("Train", resourceCulture);
        internal static string Attack => ResourceManager.GetString("Attack", resourceCulture);
        internal static string Defense => ResourceManager.GetString("Defense", resourceCulture);
        internal static string Speed => ResourceManager.GetString("Speed", resourceCulture);
        internal static string Cost => ResourceManager.GetString("Cost", resourceCulture);
        internal static string Manpower => ResourceManager.GetString("Manpower", resourceCulture);
    }
}
